management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.web.servlet: DEBUG
    org.springframework.web.servlet: DEBUG